//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace patternsLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_part
    {
        public int base_part_id { get; set; }
        public string base_part_name { get; set; }
        public string base_part_description { get; set; }
        public string base_part_pic { get; set; }
        public string base_part_info { get; set; }
        public int art_id { get; set; }
    
        public virtual article article { get; set; }
    }
}
