//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace patternsLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_source
    {
        public int list_id { get; set; }
        public string list_name { get; set; }
        public string list_author { get; set; }
        public string list_type { get; set; }
        public string list_url { get; set; }
        public Nullable<int> sec_id { get; set; }
    
        public virtual section section { get; set; }
    }
}
